// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: app/test-service/internal/conf/config.conf.proto

package conf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BusinessConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BusinessConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BusinessConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BusinessConfigMultiError,
// or nil if none found.
func (m *BusinessConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *BusinessConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBusiness()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BusinessConfigValidationError{
					field:  "Business",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BusinessConfigValidationError{
					field:  "Business",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBusiness()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BusinessConfigValidationError{
				field:  "Business",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BusinessConfigMultiError(errors)
	}

	return nil
}

// BusinessConfigMultiError is an error wrapping multiple validation errors
// returned by BusinessConfig.ValidateAll() if the designated constraints
// aren't met.
type BusinessConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BusinessConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BusinessConfigMultiError) AllErrors() []error { return m }

// BusinessConfigValidationError is the validation error returned by
// BusinessConfig.Validate if the designated constraints aren't met.
type BusinessConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BusinessConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BusinessConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BusinessConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BusinessConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BusinessConfigValidationError) ErrorName() string { return "BusinessConfigValidationError" }

// Error satisfies the builtin error interface
func (e BusinessConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBusinessConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BusinessConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BusinessConfigValidationError{}

// Validate checks the field values on BusinessConfig_Business with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BusinessConfig_Business) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BusinessConfig_Business with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BusinessConfig_BusinessMultiError, or nil if none found.
func (m *BusinessConfig_Business) ValidateAll() error {
	return m.validate(true)
}

func (m *BusinessConfig_Business) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetKey() != "" {

	}

	if len(errors) > 0 {
		return BusinessConfig_BusinessMultiError(errors)
	}

	return nil
}

// BusinessConfig_BusinessMultiError is an error wrapping multiple validation
// errors returned by BusinessConfig_Business.ValidateAll() if the designated
// constraints aren't met.
type BusinessConfig_BusinessMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BusinessConfig_BusinessMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BusinessConfig_BusinessMultiError) AllErrors() []error { return m }

// BusinessConfig_BusinessValidationError is the validation error returned by
// BusinessConfig_Business.Validate if the designated constraints aren't met.
type BusinessConfig_BusinessValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BusinessConfig_BusinessValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BusinessConfig_BusinessValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BusinessConfig_BusinessValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BusinessConfig_BusinessValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BusinessConfig_BusinessValidationError) ErrorName() string {
	return "BusinessConfig_BusinessValidationError"
}

// Error satisfies the builtin error interface
func (e BusinessConfig_BusinessValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBusinessConfig_Business.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BusinessConfig_BusinessValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BusinessConfig_BusinessValidationError{}
