// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.30.2
// source: api/nodeid-service/v1/resources/node_event.resource.v1.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRenewalNodeIdEventReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeRenewalNodeIdEventReq) Reset() {
	*x = SubscribeRenewalNodeIdEventReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRenewalNodeIdEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRenewalNodeIdEventReq) ProtoMessage() {}

func (x *SubscribeRenewalNodeIdEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRenewalNodeIdEventReq.ProtoReflect.Descriptor instead.
func (*SubscribeRenewalNodeIdEventReq) Descriptor() ([]byte, []int) {
	return file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescGZIP(), []int{0}
}

type SubscribeRenewalNodeIdEventResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32                                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason   string                               `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message  string                               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Metadata map[string]string                    `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data     *SubscribeRenewalNodeIdEventRespData `protobuf:"bytes,100,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SubscribeRenewalNodeIdEventResp) Reset() {
	*x = SubscribeRenewalNodeIdEventResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRenewalNodeIdEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRenewalNodeIdEventResp) ProtoMessage() {}

func (x *SubscribeRenewalNodeIdEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRenewalNodeIdEventResp.ProtoReflect.Descriptor instead.
func (*SubscribeRenewalNodeIdEventResp) Descriptor() ([]byte, []int) {
	return file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRenewalNodeIdEventResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubscribeRenewalNodeIdEventResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SubscribeRenewalNodeIdEventResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubscribeRenewalNodeIdEventResp) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SubscribeRenewalNodeIdEventResp) GetData() *SubscribeRenewalNodeIdEventRespData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubscribeRenewalNodeIdEventRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumerCounter int64 `protobuf:"varint,1,opt,name=consumer_counter,json=consumerCounter,proto3" json:"consumer_counter,omitempty"`
}

func (x *SubscribeRenewalNodeIdEventRespData) Reset() {
	*x = SubscribeRenewalNodeIdEventRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRenewalNodeIdEventRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRenewalNodeIdEventRespData) ProtoMessage() {}

func (x *SubscribeRenewalNodeIdEventRespData) ProtoReflect() protoreflect.Message {
	mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRenewalNodeIdEventRespData.ProtoReflect.Descriptor instead.
func (*SubscribeRenewalNodeIdEventRespData) Descriptor() ([]byte, []int) {
	return file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRenewalNodeIdEventRespData) GetConsumerCounter() int64 {
	if x != nil {
		return x.ConsumerCounter
	}
	return 0
}

type StopRenewalNodeIdEventReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopRenewalNodeIdEventReq) Reset() {
	*x = StopRenewalNodeIdEventReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRenewalNodeIdEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRenewalNodeIdEventReq) ProtoMessage() {}

func (x *StopRenewalNodeIdEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRenewalNodeIdEventReq.ProtoReflect.Descriptor instead.
func (*StopRenewalNodeIdEventReq) Descriptor() ([]byte, []int) {
	return file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescGZIP(), []int{3}
}

type StopRenewalNodeIdEventResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason   string                          `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message  string                          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Metadata map[string]string               `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data     *StopRenewalNodeIdEventRespData `protobuf:"bytes,100,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StopRenewalNodeIdEventResp) Reset() {
	*x = StopRenewalNodeIdEventResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRenewalNodeIdEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRenewalNodeIdEventResp) ProtoMessage() {}

func (x *StopRenewalNodeIdEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRenewalNodeIdEventResp.ProtoReflect.Descriptor instead.
func (*StopRenewalNodeIdEventResp) Descriptor() ([]byte, []int) {
	return file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescGZIP(), []int{4}
}

func (x *StopRenewalNodeIdEventResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StopRenewalNodeIdEventResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StopRenewalNodeIdEventResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopRenewalNodeIdEventResp) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StopRenewalNodeIdEventResp) GetData() *StopRenewalNodeIdEventRespData {
	if x != nil {
		return x.Data
	}
	return nil
}

type StopRenewalNodeIdEventRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumerCounter int64 `protobuf:"varint,1,opt,name=consumer_counter,json=consumerCounter,proto3" json:"consumer_counter,omitempty"`
}

func (x *StopRenewalNodeIdEventRespData) Reset() {
	*x = StopRenewalNodeIdEventRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRenewalNodeIdEventRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRenewalNodeIdEventRespData) ProtoMessage() {}

func (x *StopRenewalNodeIdEventRespData) ProtoReflect() protoreflect.Message {
	mi := &file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRenewalNodeIdEventRespData.ProtoReflect.Descriptor instead.
func (*StopRenewalNodeIdEventRespData) Descriptor() ([]byte, []int) {
	return file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescGZIP(), []int{5}
}

func (x *StopRenewalNodeIdEventRespData) GetConsumerCounter() int64 {
	if x != nil {
		return x.ConsumerCounter
	}
	return 0
}

var File_api_nodeid_service_v1_resources_node_event_resource_v1_proto protoreflect.FileDescriptor

var file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a,
	0x73, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x2e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76, 0x31, 0x22, 0x20, 0x0a, 0x1e, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x22, 0xe0, 0x02, 0x0a,
	0x1f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61,
	0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x65, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x49, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52,
	0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x53, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x73, 0x61,
	0x61, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x50, 0x0a, 0x23, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x6e, 0x65,
	0x77, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x22, 0xd1,
	0x02, 0x0a, 0x1a, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x60, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x44, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x4e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x64, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x73, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x69, 0x64, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x4b, 0x0a, 0x1e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61,
	0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42,
	0x8b, 0x01, 0x0a, 0x1a, 0x73, 0x61, 0x61, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x69, 0x64, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76, 0x31, 0x42, 0x17,
	0x53, 0x61, 0x61, 0x73, 0x41, 0x70, 0x69, 0x4e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x73,
	0x61, 0x61, 0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x3b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescOnce sync.Once
	file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescData = file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDesc
)

func file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescGZIP() []byte {
	file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescOnce.Do(func() {
		file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescData)
	})
	return file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDescData
}

var file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_goTypes = []any{
	(*SubscribeRenewalNodeIdEventReq)(nil),      // 0: saas.api.nodeid.resourcev1.SubscribeRenewalNodeIdEventReq
	(*SubscribeRenewalNodeIdEventResp)(nil),     // 1: saas.api.nodeid.resourcev1.SubscribeRenewalNodeIdEventResp
	(*SubscribeRenewalNodeIdEventRespData)(nil), // 2: saas.api.nodeid.resourcev1.SubscribeRenewalNodeIdEventRespData
	(*StopRenewalNodeIdEventReq)(nil),           // 3: saas.api.nodeid.resourcev1.StopRenewalNodeIdEventReq
	(*StopRenewalNodeIdEventResp)(nil),          // 4: saas.api.nodeid.resourcev1.StopRenewalNodeIdEventResp
	(*StopRenewalNodeIdEventRespData)(nil),      // 5: saas.api.nodeid.resourcev1.StopRenewalNodeIdEventRespData
	nil,                                         // 6: saas.api.nodeid.resourcev1.SubscribeRenewalNodeIdEventResp.MetadataEntry
	nil,                                         // 7: saas.api.nodeid.resourcev1.StopRenewalNodeIdEventResp.MetadataEntry
}
var file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_depIdxs = []int32{
	6, // 0: saas.api.nodeid.resourcev1.SubscribeRenewalNodeIdEventResp.metadata:type_name -> saas.api.nodeid.resourcev1.SubscribeRenewalNodeIdEventResp.MetadataEntry
	2, // 1: saas.api.nodeid.resourcev1.SubscribeRenewalNodeIdEventResp.data:type_name -> saas.api.nodeid.resourcev1.SubscribeRenewalNodeIdEventRespData
	7, // 2: saas.api.nodeid.resourcev1.StopRenewalNodeIdEventResp.metadata:type_name -> saas.api.nodeid.resourcev1.StopRenewalNodeIdEventResp.MetadataEntry
	5, // 3: saas.api.nodeid.resourcev1.StopRenewalNodeIdEventResp.data:type_name -> saas.api.nodeid.resourcev1.StopRenewalNodeIdEventRespData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_init() }
func file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_init() {
	if File_api_nodeid_service_v1_resources_node_event_resource_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRenewalNodeIdEventReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRenewalNodeIdEventResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRenewalNodeIdEventRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StopRenewalNodeIdEventReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StopRenewalNodeIdEventResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*StopRenewalNodeIdEventRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_goTypes,
		DependencyIndexes: file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_depIdxs,
		MessageInfos:      file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_msgTypes,
	}.Build()
	File_api_nodeid_service_v1_resources_node_event_resource_v1_proto = out.File
	file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_rawDesc = nil
	file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_goTypes = nil
	file_api_nodeid_service_v1_resources_node_event_resource_v1_proto_depIdxs = nil
}
