// Package data
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package data

import (
	"bytes"
	context "context"
	"database/sql"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-micro-saas/nodeid-service/app/nodeid-service/internal/data/po"
	"github.com/go-micro-saas/nodeid-service/app/nodeid-service/internal/data/repo"
	schemas "github.com/go-micro-saas/nodeid-service/app/nodeid-service/internal/data/schema/node_serial"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
	errorpkg "github.com/ikaiguang/go-srv-kit/kratos/error"
	gorm "gorm.io/gorm"
	"strings"
)

// nodeSerialData repo
type nodeSerialData struct {
	log              *log.Helper
	dbConn           *gorm.DB           // *gorm.DB
	NodeSerialSchema schemas.NodeSerial // NodeSerial
}

// NewNodeSerialData new data repo
func NewNodeSerialData(logger log.Logger, dbConn *gorm.DB) datarepos.NodeSerialDataRepo {
	logHelper := log.NewHelper(log.With(logger, "module", "nodeid-service/data/data"))
	return &nodeSerialData{
		log:    logHelper,
		dbConn: dbConn,
	}
}

func (s *nodeSerialData) NewTransaction(ctx context.Context, opts ...*sql.TxOptions) gormpkg.TransactionInterface {
	return gormpkg.NewTransaction(ctx, s.dbConn, opts...)
}

// =============== 创建 ===============

// create insert one
func (s *nodeSerialData) create(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		Create(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// Create insert one
func (s *nodeSerialData) Create(ctx context.Context, dataModel *po.NodeSerial) error {
	return s.create(ctx, s.dbConn, dataModel)
}

// CreateWithDBConn create
func (s *nodeSerialData) CreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) error {
	return s.create(ctx, dbConn, dataModel)
}

// FirstOrCreate ...
func (s *nodeSerialData) FirstOrCreate(ctx context.Context, dataModel *po.NodeSerial) (*po.NodeSerial, error) {
	err := s.dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		Where(schemas.FieldInstanceId+" = ?", dataModel.InstanceId).
		FirstOrCreate(dataModel).Error
	if err != nil {
		if gormpkg.IsErrDuplicatedKey(err) {
			err = nil
			goto getExistData
		}
		e := errorpkg.ErrorInternalServer("")
		return nil, errorpkg.Wrap(e, err)
	}
	return dataModel, nil
getExistData:
	err = s.dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		Where(schemas.FieldInstanceId+" = ?", dataModel.InstanceId).
		First(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return nil, errorpkg.Wrap(e, err)
	}
	return dataModel, nil
}

// existCreate exist create
func (s *nodeSerialData) existCreate(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) (anotherModel *po.NodeSerial, isNotFound bool, err error) {
	anotherModel = new(po.NodeSerial)
	err = dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			isNotFound = true
			err = nil
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// ExistCreate exist create
func (s *nodeSerialData) ExistCreate(ctx context.Context, dataModel *po.NodeSerial) (anotherModel *po.NodeSerial, isNotFound bool, err error) {
	return s.existCreate(ctx, s.dbConn, dataModel)
}

// ExistCreateWithDBConn exist create
func (s *nodeSerialData) ExistCreateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) (anotherModel *po.NodeSerial, isNotFound bool, err error) {
	return s.existCreate(ctx, dbConn, dataModel)
}

// createInBatches create many
func (s *nodeSerialData) createInBatches(ctx context.Context, dbConn *gorm.DB, dataModels []*po.NodeSerial, batchSize int) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		CreateInBatches(dataModels, batchSize).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// CreateInBatches create many
func (s *nodeSerialData) CreateInBatches(ctx context.Context, dataModels []*po.NodeSerial, batchSize int) error {
	return s.createInBatches(ctx, s.dbConn, dataModels, batchSize)
}

// CreateInBatchesWithDBConn create many
func (s *nodeSerialData) CreateInBatchesWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*po.NodeSerial, batchSize int) error {
	return s.createInBatches(ctx, dbConn, dataModels, batchSize)
}

// =============== 更新 ===============

// update update
func (s *nodeSerialData) update(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		// Where(schemas.FieldId+" = ?", dataModel.Id).
		Save(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// Update update
func (s *nodeSerialData) Update(ctx context.Context, dataModel *po.NodeSerial) error {
	return s.update(ctx, s.dbConn, dataModel)
}

// UpdateWithDBConn update
func (s *nodeSerialData) UpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) error {
	return s.update(ctx, dbConn, dataModel)
}

func (s *nodeSerialData) UpdateNodeIDWithTransaction(ctx context.Context, tx gormpkg.TransactionInterface, dataModel *po.NodeSerial) (err error) {
	fc := func(ctx context.Context, tx *gorm.DB) error {
		updates := map[string]interface{}{
			schemas.FieldCurrentNodeId: dataModel.CurrentNodeId,
			schemas.FieldUpdatedTime:   dataModel.UpdatedTime,
		}
		err = tx.WithContext(ctx).
			Table(s.NodeSerialSchema.TableName()).
			Where(schemas.FieldInstanceId+" = ?", dataModel.InstanceId).
			UpdateColumns(updates).Error
		return err
	}
	err = tx.Do(ctx, fc)
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		return errorpkg.Wrap(e, err)
	}
	return
}

// existUpdate exist update
func (s *nodeSerialData) existUpdate(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) (anotherModel *po.NodeSerial, isNotFound bool, err error) {
	anotherModel = new(po.NodeSerial)
	err = dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		Where(schemas.FieldId+" != ?", dataModel.Id).
		First(anotherModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			isNotFound = true
			err = nil
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// ExistUpdate exist update
func (s *nodeSerialData) ExistUpdate(ctx context.Context, dataModel *po.NodeSerial) (anotherModel *po.NodeSerial, isNotFound bool, err error) {
	return s.existUpdate(ctx, s.dbConn, dataModel)
}

// ExistUpdateWithDBConn exist update
func (s *nodeSerialData) ExistUpdateWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) (anotherModel *po.NodeSerial, isNotFound bool, err error) {
	return s.existUpdate(ctx, dbConn, dataModel)
}

// =============== query one : 查一个 ===============

// queryOneById query one by id
func (s *nodeSerialData) queryOneById(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *po.NodeSerial, isNotFound bool, err error) {
	dataModel = new(po.NodeSerial)
	err = dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		Where(schemas.FieldId+" = ?", id).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// QueryOneById query one by id
func (s *nodeSerialData) QueryOneById(ctx context.Context, id interface{}) (dataModel *po.NodeSerial, isNotFound bool, err error) {
	return s.queryOneById(ctx, s.dbConn, id)
}

// QueryOneByIdWithDBConn query one by id
func (s *nodeSerialData) QueryOneByIdWithDBConn(ctx context.Context, dbConn *gorm.DB, id interface{}) (dataModel *po.NodeSerial, isNotFound bool, err error) {
	return s.queryOneById(ctx, dbConn, id)
}

func (s *nodeSerialData) QueryOneByIdForUpdate(ctx context.Context, tx gormpkg.TransactionInterface, id uint64) (dataModel *po.NodeSerial, err error) {
	dataModel = new(po.NodeSerial)
	fc := func(ctx context.Context, tx *gorm.DB) error {
		tx = tx.WithContext(ctx).
			Table(s.NodeSerialSchema.TableName()).
			Where(schemas.FieldId+" = ?", id)

		return gormpkg.ForUpdate(tx).First(dataModel).Error
	}
	err = tx.Do(ctx, fc)
	if err != nil {
		//if gormpkg.IsErrRecordNotFound(err) {
		//	err = nil
		//	isNotFound = true
		//} else {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	}
	return
}

// queryOneByConditions query one by conditions
func (s *nodeSerialData) queryOneByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *po.NodeSerial, isNotFound bool, err error) {
	dataModel = new(po.NodeSerial)
	dbConn = dbConn.WithContext(ctx).Table(s.NodeSerialSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		First(dataModel).Error
	if err != nil {
		if gormpkg.IsErrRecordNotFound(err) {
			err = nil
			isNotFound = true
		} else {
			e := errorpkg.ErrorInternalServer("")
			err = errorpkg.Wrap(e, err)
		}
		return
	}
	return
}

// QueryOneByConditions query one by conditions
func (s *nodeSerialData) QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.NodeSerial, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, s.dbConn, conditions)
}

// QueryOneByConditionsWithDBConn query one by conditions
func (s *nodeSerialData) QueryOneByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModel *po.NodeSerial, isNotFound bool, err error) {
	return s.queryOneByConditions(ctx, dbConn, conditions)
}

// =============== query all : 查全部 ===============

// queryAllByConditions query all by conditions
func (s *nodeSerialData) queryAllByConditions(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) (dataModels []*po.NodeSerial, err error) {
	dbConn = dbConn.WithContext(ctx).Table(s.NodeSerialSchema.TableName())
	err = s.WhereConditions(dbConn, conditions).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return dataModels, err
	}
	return
}

// QueryAllByConditions query all by conditions
func (s *nodeSerialData) QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) ([]*po.NodeSerial, error) {
	return s.queryAllByConditions(ctx, s.dbConn, conditions)
}

// QueryAllByConditionsWithDBConn query all by conditions
func (s *nodeSerialData) QueryAllByConditionsWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}) ([]*po.NodeSerial, error) {
	return s.queryAllByConditions(ctx, dbConn, conditions)
}

// =============== list : 列表 ===============

// list 列表
func (s *nodeSerialData) list(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.NodeSerial, recordCount int64, err error) {
	// query where
	dbConn = dbConn.WithContext(ctx).Table(s.NodeSerialSchema.TableName())
	dbConn = s.WhereConditions(dbConn, conditions)
	dbConn = gormpkg.AssembleWheres(dbConn, paginatorArgs.PageWheres)

	err = dbConn.Count(&recordCount).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	} else if recordCount == 0 {
		return // empty
	}

	// pagination
	dbConn = gormpkg.AssembleOrders(dbConn, paginatorArgs.PageOrders)
	err = gormpkg.Paginator(dbConn, paginatorArgs.PageOption).
		Find(&dataModels).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return
	}
	return
}

// List 列表
func (s *nodeSerialData) List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) ([]*po.NodeSerial, int64, error) {
	return s.list(ctx, s.dbConn, conditions, paginatorArgs)
}

// ListWithDBConn 列表
func (s *nodeSerialData) ListWithDBConn(ctx context.Context, dbConn *gorm.DB, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) ([]*po.NodeSerial, int64, error) {
	return s.list(ctx, dbConn, conditions, paginatorArgs)
}

// =============== delete : 删除 ===============

// delete delete one
func (s *nodeSerialData) delete(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		Where(schemas.FieldId+" = ?", dataModel.Id).
		Delete(dataModel).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return
}

// Delete delete one
func (s *nodeSerialData) Delete(ctx context.Context, dataModel *po.NodeSerial) error {
	return s.delete(ctx, s.dbConn, dataModel)
}

// DeleteWithDBConn delete one
func (s *nodeSerialData) DeleteWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModel *po.NodeSerial) error {
	return s.delete(ctx, dbConn, dataModel)
}

// deleteByIds delete by ids
func (s *nodeSerialData) deleteByIds(ctx context.Context, dbConn *gorm.DB, ids interface{}) (err error) {
	err = dbConn.WithContext(ctx).
		Table(s.NodeSerialSchema.TableName()).
		Where(schemas.FieldId+" in (?)", ids).
		Delete(po.NodeSerial{}).Error
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return
}

// DeleteByIds delete by ids
func (s *nodeSerialData) DeleteByIds(ctx context.Context, ids interface{}) error {
	return s.deleteByIds(ctx, s.dbConn, ids)
}

// DeleteByIdsWithDBConn delete by ids
func (s *nodeSerialData) DeleteByIdsWithDBConn(ctx context.Context, dbConn *gorm.DB, ids interface{}) error {
	return s.deleteByIds(ctx, dbConn, ids)
}

// =============== insert : 批量入库 ===============

var _ gormpkg.BatchInsertRepo = new(NodeSerialSlice)

// NodeSerialSlice 表切片
type NodeSerialSlice []*po.NodeSerial

// TableName 表名
func (s *NodeSerialSlice) TableName() string {
	return schemas.NodeSerialSchema.TableName()
}

// Len 长度
func (s *NodeSerialSlice) Len() int {
	return len(*s)
}

// InsertColumns 批量入库的列
func (s *NodeSerialSlice) InsertColumns() (columnList []string, placeholder string) {
	// columns
	columnList = []string{
		schemas.FieldCreatedTime, schemas.FieldUpdatedTime,
		schemas.FieldInstanceId, schemas.FieldCurrentNodeId,
	}

	// placeholders
	insertPlaceholderBytes := bytes.Repeat([]byte("?, "), len(columnList))
	insertPlaceholderBytes = bytes.TrimSuffix(insertPlaceholderBytes, []byte(", "))

	return columnList, string(insertPlaceholderBytes)
}

// InsertValues 批量入库的值
func (s *NodeSerialSlice) InsertValues(args *gormpkg.BatchInsertValueArgs) (prepareData []interface{}, placeholderSlice []string) {
	dataModels := (*s)[args.StepStart:args.StepEnd]
	for index := range dataModels {
		// placeholder
		placeholderSlice = append(placeholderSlice, "("+args.InsertPlaceholder+")")

		// prepare data
		prepareData = append(prepareData, dataModels[index].CreatedTime)
		prepareData = append(prepareData, dataModels[index].UpdatedTime)
		prepareData = append(prepareData, dataModels[index].InstanceId)
		prepareData = append(prepareData, dataModels[index].CurrentNodeId)
	}
	return prepareData, placeholderSlice
}

// UpdateColumns 批量入库的列
func (s *NodeSerialSlice) UpdateColumns() (columnList []string) {
	// columns
	columnList = []string{
		schemas.FieldCreatedTime + "=excluded." + schemas.FieldCreatedTime,
		schemas.FieldUpdatedTime + "=excluded." + schemas.FieldUpdatedTime,
		schemas.FieldInstanceId + "=excluded." + schemas.FieldInstanceId,
		schemas.FieldCurrentNodeId + "=excluded." + schemas.FieldCurrentNodeId,
	}
	return columnList
}

// ConflictActionForMySQL 更新冲突时的操作
func (s *NodeSerialSlice) ConflictActionForMySQL() (req *gormpkg.BatchInsertConflictActionReq) {
	req = &gormpkg.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "AS excluded",
		OnConflictTarget:      "ON DUPLICATE KEY",
		OnConflictAction:      "UPDATE " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// ConflictActionForPostgres 更新冲突时的操作
func (s *NodeSerialSlice) ConflictActionForPostgres() (req *gormpkg.BatchInsertConflictActionReq) {
	req = &gormpkg.BatchInsertConflictActionReq{
		OnConflictValueAlias:  "",
		OnConflictTarget:      "ON CONFLICT(id)",
		OnConflictAction:      "DO UPDATE SET " + strings.Join(s.UpdateColumns(), ", "),
		OnConflictPrepareData: nil,
	}
	return req
}

// insert 批量插入
func (s *nodeSerialData) insert(ctx context.Context, dbConn *gorm.DB, dataModels NodeSerialSlice) error {
	err := gormpkg.BatchInsertWithContext(ctx, dbConn, &dataModels)
	if err != nil {
		e := errorpkg.ErrorInternalServer("")
		err = errorpkg.Wrap(e, err)
		return err
	}
	return nil
}

// Insert 批量插入
func (s *nodeSerialData) Insert(ctx context.Context, dataModels []*po.NodeSerial) error {
	return s.insert(ctx, s.dbConn, dataModels)
}

// InsertWithDBConn 批量插入
func (s *nodeSerialData) InsertWithDBConn(ctx context.Context, dbConn *gorm.DB, dataModels []*po.NodeSerial) error {
	return s.insert(ctx, dbConn, dataModels)
}

// =============== conditions : 条件 ===============

// WhereConditions orm where
func (s *nodeSerialData) WhereConditions(dbConn *gorm.DB, conditions map[string]interface{}) *gorm.DB {

	// table name
	// tableName := s.NodeSerialSchema.TableName()

	// On-demand loading

	// id
	// if data, ok := conditions[schemas.FieldId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldId+" = ?", data)
	// }

	// created_time
	// if data, ok := conditions[schemas.FieldCreatedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldCreatedTime+" = ?", data)
	// }

	// updated_time
	// if data, ok := conditions[schemas.FieldUpdatedTime]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldUpdatedTime+" = ?", data)
	// }

	// instance_id
	// if data, ok := conditions[schemas.FieldInstanceId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldInstanceId+" = ?", data)
	// }

	// current_node_id
	// if data, ok := conditions[schemas.FieldCurrentNodeId]; ok {
	// 	   dbConn = dbConn.Where(tableName+"."+schemas.FieldCurrentNodeId+" = ?", data)
	// }

	return dbConn
}

// UpdateColumns update columns
func (s *nodeSerialData) UpdateColumns(conditions map[string]interface{}) map[string]interface{} {

	// update columns
	updateColumns := make(map[string]interface{})

	// On-demand loading

	// id
	//if data, ok := conditions[schemas.FieldId]; ok {
	//	updateColumns[schemas.FieldId] = data
	//}

	// created_time
	//if data, ok := conditions[schemas.FieldCreatedTime]; ok {
	//	updateColumns[schemas.FieldCreatedTime] = data
	//}

	// updated_time
	//if data, ok := conditions[schemas.FieldUpdatedTime]; ok {
	//	updateColumns[schemas.FieldUpdatedTime] = data
	//}

	// instance_id
	//if data, ok := conditions[schemas.FieldInstanceId]; ok {
	//	updateColumns[schemas.FieldInstanceId] = data
	//}

	// current_node_id
	//if data, ok := conditions[schemas.FieldCurrentNodeId]; ok {
	//	updateColumns[schemas.FieldCurrentNodeId] = data
	//}

	return updateColumns
}
