version: '3'

services:
  dev-nodeid-service:
    image: nodeid-service:latest
    container_name: dev-nodeid-service
    ports:
      - "10201:10201"
      - "10202:10202"
    networks:
      - my-network
    volumes:
      - dev_nodeid_service_data:/myworkspace/golang/src/workspace/runtime
      - ./configs:/myworkspace/golang/src/workspace/configs
    environment:
      TZ: Asia/Shanghai
    #entrypoint: ["/bin/bash"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10201/api/v1/nodeid/get-service-info" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  my-network: # 已有的网络的名称
    external: true  # 标记为外部网络，表示这是已存在的网络

volumes:
  dev_nodeid_service_data:
    driver: local
