nodeid_service:
  # 节点范围；最小节点默认值：1；最大节点默认值：1023；
  min_node_id: 1
  max_node_id: 1023
  node_epoch: 2024-12-11T18:37:50+08:00
  # 空闲释放时间；默认：100s。
  idle_duration: 100s
  # 心跳续订延长的时间；默认：30s。范围：[1, idle_duration]；延长有效期：now()+idle_duration
  heartbeat_interval: 30s

uuid_service:
  instance_id: uuid-service
  instance_name: uuid-service
  metadata:
    service: uuid-service
