// Package repos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"github.com/go-micro-saas/nodeid-service/app/nodeid-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// NodeSerialDataRepo repo
type NodeSerialDataRepo interface {
	Create(ctx context.Context, dataModel *po.NodeSerial) error
	ExistCreate(ctx context.Context, dataModel *po.NodeSerial) (anotherModel *po.NodeSerial, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.NodeSerial, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.NodeSerial) error
	Update(ctx context.Context, dataModel *po.NodeSerial) error
	ExistUpdate(ctx context.Context, dataModel *po.NodeSerial) (anotherModel *po.NodeSerial, isNotFound bool, err error)
	FirstOrCreate(ctx context.Context, dataModel *po.NodeSerial) (*po.NodeSerial, error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.NodeSerial, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.NodeSerial, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.NodeSerial, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.NodeSerial, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.NodeSerial) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
