// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"database/sql"
	"github.com/go-micro-saas/nodeid-service/app/nodeid-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
	"time"
)

// NodeIdDataRepo repo
type NodeIdDataRepo interface {
	NewTransaction(ctx context.Context, opts ...*sql.TxOptions) gormpkg.TransactionInterface
	Create(ctx context.Context, dataModel *po.NodeId) error
	ExistCreate(ctx context.Context, dataModel *po.NodeId) (anotherModel *po.NodeId, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.NodeId, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.NodeId) error
	Update(ctx context.Context, dataModel *po.NodeId) error
	ExistUpdate(ctx context.Context, dataModel *po.NodeId) (anotherModel *po.NodeId, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.NodeId, isNotFound bool, err error)
	QueryOneIdleNodeIdByInstanceId(ctx context.Context, instanceID string) (dataModel *po.NodeId, isNotFound bool, err error)
	QueryOneExpiredNodeIdByInstanceId(ctx context.Context, instanceID string, expiredTime time.Time) (dataModel *po.NodeId, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.NodeId, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.NodeId, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.NodeId, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.NodeId) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
