// Package datarepos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package datarepos

import (
	context "context"
	"github.com/go-micro-saas/nodeid-service/app/nodeid-service/internal/data/po"
	gormpkg "github.com/ikaiguang/go-srv-kit/data/gorm"
)

// NodeEventHistoryRepo repo
type NodeEventHistoryRepo interface {
	Create(ctx context.Context, dataModel *po.NodeEventHistory) error
	ExistCreate(ctx context.Context, dataModel *po.NodeEventHistory) (anotherModel *po.NodeEventHistory, isNotFound bool, err error)
	CreateInBatches(ctx context.Context, dataModels []*po.NodeEventHistory, batchSize int) error
	Insert(ctx context.Context, dataModels []*po.NodeEventHistory) error
	Update(ctx context.Context, dataModel *po.NodeEventHistory) error
	ExistUpdate(ctx context.Context, dataModel *po.NodeEventHistory) (anotherModel *po.NodeEventHistory, isNotFound bool, err error)
	QueryOneById(ctx context.Context, id interface{}) (dataModel *po.NodeEventHistory, isNotFound bool, err error)
	QueryOneByConditions(ctx context.Context, conditions map[string]interface{}) (dataModel *po.NodeEventHistory, isNotFound bool, err error)
	QueryAllByConditions(ctx context.Context, conditions map[string]interface{}) (dataModels []*po.NodeEventHistory, err error)
	List(ctx context.Context, conditions map[string]interface{}, paginatorArgs *gormpkg.PaginatorArgs) (dataModels []*po.NodeEventHistory, totalNumber int64, err error)
	Delete(ctx context.Context, dataModel *po.NodeEventHistory) error
	DeleteByIds(ctx context.Context, ids interface{}) error
}
