// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.6
// source: api/test-service/v1/services/test.service.v1.proto

package servicev1

import (
	context "context"
	resources "github.com/go-micro-saas/node-id-service/api/test-service/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SrvTestV1_Ping_FullMethodName = "/saas.api.nodeid_test.servicev1.SrvTestV1/Ping"
)

// SrvTestV1Client is the client API for SrvTestV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvTestV1Client interface {
	// ping
	Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error)
}

type srvTestV1Client struct {
	cc grpc.ClientConnInterface
}

func NewSrvTestV1Client(cc grpc.ClientConnInterface) SrvTestV1Client {
	return &srvTestV1Client{cc}
}

func (c *srvTestV1Client) Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error) {
	out := new(resources.PingResp)
	err := c.cc.Invoke(ctx, SrvTestV1_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvTestV1Server is the server API for SrvTestV1 service.
// All implementations must embed UnimplementedSrvTestV1Server
// for forward compatibility
type SrvTestV1Server interface {
	// ping
	Ping(context.Context, *resources.PingReq) (*resources.PingResp, error)
	mustEmbedUnimplementedSrvTestV1Server()
}

// UnimplementedSrvTestV1Server must be embedded to have forward compatible implementations.
type UnimplementedSrvTestV1Server struct {
}

func (UnimplementedSrvTestV1Server) Ping(context.Context, *resources.PingReq) (*resources.PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSrvTestV1Server) mustEmbedUnimplementedSrvTestV1Server() {}

// UnsafeSrvTestV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvTestV1Server will
// result in compilation errors.
type UnsafeSrvTestV1Server interface {
	mustEmbedUnimplementedSrvTestV1Server()
}

func RegisterSrvTestV1Server(s grpc.ServiceRegistrar, srv SrvTestV1Server) {
	s.RegisterService(&SrvTestV1_ServiceDesc, srv)
}

func _SrvTestV1_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvTestV1Server).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrvTestV1_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvTestV1Server).Ping(ctx, req.(*resources.PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvTestV1_ServiceDesc is the grpc.ServiceDesc for SrvTestV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvTestV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saas.api.nodeid_test.servicev1.SrvTestV1",
	HandlerType: (*SrvTestV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SrvTestV1_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/test-service/v1/services/test.service.v1.proto",
}
